thesis_bulletin:
    resource: "@ThesisBulletinBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
fos_user_registration_register:
    pattern:  /register
    defaults: { _controller: ThesisBulletinBundle:Registration:register }
    options:
        expose: true
        
announcements:
    type: rest
    resource: Thesis\BulletinBundle\Controller\AnnouncementController
    options:
        expose: true
        
colleges:
    type: rest
    resource: Thesis\BulletinBundle\Controller\CollegeController
    options:
        expose: true
        
departments:
    type: rest
    resource: Thesis\BulletinBundle\Controller\DepartmentController
    options:
        expose: true
        
faculty:
    type: rest
    resource: Thesis\BulletinBundle\Controller\FacultyController
    options:
        expose: true
    
users:
    type: rest
    resource: Thesis\BulletinBundle\Controller\UserController
    options:
        expose: true
        
fos_user_security_login:
    pattern:  /login
    defaults: { _controller: ThesisBulletinBundle:Security:login }
    options:
        expose: true
        
fos_user_security_logout:
    pattern:  /logout
    defaults: { _controller: ThesisBulletinBundle:Security:logout }
    options:
        expose: true
