<?php

namespace Thesis\BulletinBundle\Entity;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends \Doctrine\ORM\EntityRepository {

    public function findOtherUsers($id) {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('u')
                        ->from('ThesisBulletinBundle:User', 'u')
                        ->where('u.id != :id')
                        ->orderBy('u.username')
                        ->setParameter(':id', $id)
                        ->getQuery()
                        ->getResult();
    }

    public function findAllSorted() {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('a')
                        ->from('ThesisBulletinBundle:Announcement', 'a')
                        ->orderBy('a.priorityLvl', 'asc')
                        ->addOrderBy('a.datePosted', 'desc')
                        ->addOrderBy('a.title', 'asc')
                        ->getQuery()
                        ->getResult()
        ;
    }

}
