<?php

namespace Thesis\BulletinBundle\Entity;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllSorted() {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('a')
                        ->from('ThesisBulletinBundle:Announcement', 'a')
                        ->orderBy('a.priorityLvl', 'asc')
                        ->addOrderBy('a.datePosted', 'desc')
                        ->addOrderBy('a.title', 'asc')
                        ->getQuery()
                        ->getResult()
        ;
    }

    public function findVisible($id) {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('a')
                        ->from('ThesisBulletinBundle:Announcement', 'a')
                        ->where('a.id = :id')
                        ->andWhere('a.visible = true')
                        ->orderBy('a.priorityLvl', 'asc')
                        ->addOrderBy('a.datePosted', 'desc')
                        ->addOrderBy('a.title', 'asc')
                        ->getQuery()
                        ->getResult()
        ;
    }
    public function findSorted($id) {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('a')
                        ->from('ThesisBulletinBundle:Announcement', 'a')
                        ->where('a.id = :id')
                        ->orderBy('a.priorityLvl', 'asc')
                        ->addOrderBy('a.datePosted', 'desc')
                        ->addOrderBy('a.title', 'asc')
                        ->getQuery()
                        ->getResult()
        ;
    }

}
