<?php

namespace Thesis\BulletinBundle\Entity;

/**
 * CollegeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollegeRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllSorted() {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('c')
                        ->from('ThesisBulletinBundle:College', 'c')
                        ->orderBy('c.name', 'asc')
                        ->getQuery()
                        ->getResult()
        ;
    }

}
