<?php

namespace Thesis\BulletinBundle\Entity;

/**
 * FacultyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultyRepository extends \Doctrine\ORM\EntityRepository
{
     public function findAllSorted() {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('f')
                        ->from('ThesisBulletinBundle:Faculty', 'f')
                        ->orderBy('f.lastName', 'asc')
                        ->getQuery()
                        ->getResult()
        ;
    }
}
