<?php

namespace Thesis\BulletinBundle\Entity;

/**
 * ImageAnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageAnnouncementRepository extends \Doctrine\ORM\EntityRepository
{
}
