<?php

namespace Thesis\BulletinBundle\Entity;

/**
 * PlainAnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlainAnnouncementRepository extends \Doctrine\ORM\EntityRepository
{
}
